import json
import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from tests.helpers import ROOT


PLUGIN_ROOT = ROOT / "plugin" / "gh-address-cr"
PLUGIN_BUILDER = ROOT / "scripts" / "build_plugin_payload.py"
PYPROJECT = ROOT / "pyproject.toml"
MARKETPLACE = ROOT / ".agents" / "plugins" / "marketplace.json"
CI_WORKFLOW = ROOT / ".github" / "workflows" / "ci.yml"
RELEASE_WORKFLOW = ROOT / ".github" / "workflows" / "release.yml"
README = ROOT / "README.md"
RELEASE_CONFIG = ROOT / "release.config.cjs"


def _pyproject_version() -> str:
    match = re.search(r'^version = "([^"]+)"$', PYPROJECT.read_text(encoding="utf-8"), re.MULTILINE)
    if not match:
        raise AssertionError("pyproject.toml version not found")
    return match.group(1)


class PluginPackagingTest(unittest.TestCase):
    def build_generated_payload(self) -> tuple[tempfile.TemporaryDirectory[str], Path]:
        temp_dir = tempfile.TemporaryDirectory()
        self.addCleanup(temp_dir.cleanup)
        payload_root = Path(temp_dir.name) / "gh-address-cr"
        result = subprocess.run(
            [sys.executable, str(PLUGIN_BUILDER), "--output", str(payload_root)],
            text=True,
            capture_output=True,
            cwd=ROOT,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        return temp_dir, payload_root

    def test_plugin_manifest_has_codex_plugin_contract(self):
        _, payload_root = self.build_generated_payload()
        manifest = json.loads((payload_root / ".codex-plugin" / "plugin.json").read_text(encoding="utf-8"))
        root_manifest = json.loads((payload_root / "plugin.json").read_text(encoding="utf-8"))

        self.assertEqual(root_manifest, manifest)

        self.assertEqual(manifest["name"], "gh-address-cr")
        self.assertEqual(manifest["version"], _pyproject_version())
        self.assertEqual(manifest["skills"], "./skills/")
        self.assertNotIn("mcpServers", manifest)
        self.assertNotIn("apps", manifest)
        self.assertEqual(manifest["repository"], "https://github.com/RbBtSn0w/gh-address-cr")
        self.assertEqual(manifest["license"], "MIT")

        interface = manifest["interface"]
        self.assertEqual(interface["displayName"], "GH Address CR")
        self.assertEqual(interface["category"], "Developer Tools")
        self.assertEqual(interface["capabilities"], ["Read", "Write"])
        self.assertTrue(interface["privacyPolicyURL"].endswith("/PRIVACY.md"))
        self.assertTrue(interface["termsOfServiceURL"].endswith("/TERMS.md"))

        relative_paths = [
            manifest["skills"],
            interface["composerIcon"],
            interface["logo"],
            *interface["screenshots"],
        ]
        for raw_path in relative_paths:
            with self.subTest(path=raw_path):
                self.assertTrue(raw_path.startswith("./"))
                self.assertTrue((payload_root / raw_path[2:]).exists(), raw_path)

    def test_plugin_payload_contains_one_skill_and_no_generated_artifacts(self):
        _, payload_root = self.build_generated_payload()
        plugin_skills_root = payload_root / "skills"
        plugin_skill_root = plugin_skills_root / "gh-address-cr"

        skill_manifests = sorted(plugin_skills_root.glob("*/SKILL.md"))
        self.assertEqual(skill_manifests, [plugin_skill_root / "SKILL.md"])

        forbidden_names = {".pytest_cache", ".ruff_cache", "__pycache__", "dist", ".state"}
        for path in payload_root.rglob("*"):
            relative_path = path.relative_to(payload_root)
            with self.subTest(path=relative_path):
                self.assertTrue(forbidden_names.isdisjoint(relative_path.parts))
                self.assertNotEqual(relative_path.suffix, ".pyc")
                self.assertNotEqual(relative_path.suffix, ".log")

    def test_repo_does_not_commit_duplicated_skill_payload_tree(self):
        self.assertFalse(
            (PLUGIN_ROOT / "skills").exists(),
            "plugin/gh-address-cr/skills is generated by CI/release and must not be maintained as a committed copy",
        )

    def test_plugin_payload_check_is_reproducible(self):
        result = subprocess.run(
            [sys.executable, str(PLUGIN_BUILDER), "--check"],
            text=True,
            capture_output=True,
            cwd=ROOT,
        )

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("plugin payload can be generated", result.stdout)

    def test_community_compliance_docs_exist(self):
        privacy = (ROOT / "PRIVACY.md").read_text(encoding="utf-8")
        terms = (ROOT / "TERMS.md").read_text(encoding="utf-8")
        security = (ROOT / "SECURITY.md").read_text(encoding="utf-8")

        self.assertIn("local GitHub CLI", privacy)
        self.assertIn("GitHub side effects", privacy)
        self.assertIn("Telemetry is opt-in", privacy)
        self.assertIn("not a ChatGPT Apps SDK app", terms)
        self.assertIn("Responsible Disclosure", security)

    def test_repo_marketplace_exposes_plugin_as_local_path_in_git_marketplace(self):
        marketplace = json.loads(MARKETPLACE.read_text(encoding="utf-8"))

        self.assertEqual(marketplace["name"], "gh-address-cr-community")
        self.assertEqual(marketplace["interface"]["displayName"], "GH Address CR Community")
        self.assertEqual(len(marketplace["plugins"]), 1)

        plugin = marketplace["plugins"][0]
        self.assertEqual(plugin["name"], "gh-address-cr")
        self.assertEqual(plugin["category"], "Developer Tools")
        self.assertEqual(plugin["policy"]["installation"], "AVAILABLE")
        self.assertEqual(plugin["policy"]["authentication"], "ON_INSTALL")

        source = plugin["source"]
        self.assertEqual(source["source"], "local")
        self.assertEqual(source["path"], "./dist/plugin/gh-address-cr")
        ignore_check = subprocess.run(
            ["git", "check-ignore", "-q", source["path"][2:]],
            cwd=ROOT,
        )
        self.assertEqual(ignore_check.returncode, 0, "dist plugin path must remain an ignored generated artifact")
        generated_path = ROOT / source["path"][2:]
        if generated_path.exists():
            self.assertTrue((generated_path / ".codex-plugin" / "plugin.json").exists())

    def test_ci_and_release_generate_plugin_payload_artifacts(self):
        ci_text = CI_WORKFLOW.read_text(encoding="utf-8")
        release_text = RELEASE_WORKFLOW.read_text(encoding="utf-8")

        self.assertIn("Generate plugin payload", ci_text)
        self.assertIn("python scripts/build_plugin_payload.py --output dist/plugin/gh-address-cr", ci_text)
        self.assertNotIn("sync_scripts.py", ci_text)
        self.assertIn("Generate plugin payload", release_text)
        self.assertIn("python3 scripts/build_plugin_payload.py --output dist/plugin/gh-address-cr", release_text)
        self.assertIn("Upload plugin payload artifact", release_text)
        self.assertNotIn("sync_scripts.py", release_text)

    def test_release_version_prepare_regenerates_plugin_payload(self):
        release_config = RELEASE_CONFIG.read_text(encoding="utf-8")
        release_workflow = RELEASE_WORKFLOW.read_text(encoding="utf-8")

        self.assertIn("scripts/set_package_version.py ${nextRelease.version}", release_config)
        self.assertNotIn("scripts/build_plugin_payload.py", release_config)
        self.assertNotIn("plugin/gh-address-cr/.codex-plugin/plugin.json", release_config)
        self.assertNotIn("plugin/gh-address-cr/plugin.json", release_config)
        self.assertIn("python3 scripts/build_plugin_payload.py --output dist/plugin/gh-address-cr", release_workflow)

    def test_readme_documents_codex_marketplace_install_path(self):
        readme = README.read_text(encoding="utf-8")

        self.assertIn(".agents/plugins/marketplace.json", readme)
        self.assertIn("python3 scripts/build_plugin_payload.py --output dist/plugin/gh-address-cr", readme)
        self.assertIn("dist/plugin/gh-address-cr", readme)
        self.assertNotIn("plugin/gh-address-cr/`", readme)
        self.assertIn("curated Plugin Directory is not a self-service publish target", readme)
