"""Canonical protocol status/reason code constants — the single source of truth.


Pure constants (no imports) so any module can use these without import cycles.
Centralized to prevent silent divergence from typo'd string literals. Each
constant's value equals its name; `tests/core/test_protocol_codes.py` enforces that.
"""

from __future__ import annotations

ACTION_REJECTED = "ACTION_REJECTED"
ACTIVE_PR_LOOKUP_FAILED = "ACTIVE_PR_LOOKUP_FAILED"
BATCH_ACTION_REJECTED = "BATCH_ACTION_REJECTED"
DEPRECATION_WINDOW_OPEN = "DEPRECATION_WINDOW_OPEN"
DUPLICATE_STATE_OWNER = "DUPLICATE_STATE_OWNER"
EVIDENCE_PROFILE_REJECTED = "EVIDENCE_PROFILE_REJECTED"
FAST_FIX_ALL_REJECTED = "FAST_FIX_ALL_REJECTED"
FAST_FIX_REJECTED = "FAST_FIX_REJECTED"
GITHUB_INCOMPLETE_RESPONSE = "GITHUB_INCOMPLETE_RESPONSE"
INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
LEASE_RECOVERY_STOP = "LEASE_RECOVERY_STOP"
MALFORMED_TELEMETRY = "MALFORMED_TELEMETRY"
MISSING_CLASSIFICATION = "MISSING_CLASSIFICATION"
MISSING_FIX_REPLY_COMMIT_HASH = "MISSING_FIX_REPLY_COMMIT_HASH"
MISSING_PUBLISH_REPLY = "MISSING_PUBLISH_REPLY"
NO_ELIGIBLE_ITEM = "NO_ELIGIBLE_ITEM"
PARITY_DIFF = "PARITY_DIFF"
PUBLISH_BLOCKED = "PUBLISH_BLOCKED"
QUALITY_REGRESSION = "QUALITY_REGRESSION"
SESSION_ERROR = "SESSION_ERROR"
STALE_REQUEST_CONTEXT = "STALE_REQUEST_CONTEXT"
SYSTEM_ERROR = "SYSTEM_ERROR"
UNKNOWN_SLICE = "UNKNOWN_SLICE"
