"""Contract tests for the lease recovery surface (#273 Phase 3).

The #273 report called the recovery surface "remediation is null throughout".
Reproducing it showed two distinct defects on two different code paths:

1. **Failure path.** `LEASE_LOCKED_ITEM` did get a `remediation`, but only the
   generic `_fallback` ("read reason_code ... `address --lean`"), which names no
   lease step. And `lease_recovery` reported `recovery_outcome: "stop"` with no
   command for an agent that *owns* the lease -- a confident wrong answer, not a
   missing one.

2. **Success path.** `agent reclaim` and `agent leases` return plain payloads
   with exit 0. `remediation` is generated by `WorkflowError.to_summary`, so it
   never reached them at all. `expired_count == 0` -- the reporter's actual dead
   end -- said nothing about why nothing was reclaimed.

Note the reason codes already distinguished owner (`LEASE_ACTIVE`) from
non-owner (`LEASE_RECOVERY_STOP`); only the actionability was missing. These
tests pin that distinction rather than a new `recovery_outcome` value, which
would break `models.LEASE_RECOVERY_OUTCOMES` validation for older readers.
"""

from __future__ import annotations

import os
import re
import tempfile
import unittest
from datetime import datetime, timedelta, timezone
from unittest.mock import patch

from tests.test_control_plane_workflow import github_thread

GENERIC_FALLBACK_MARKER = "Consult `references/status-action-map.md`"


def _lease(lease_id, *, item_id, agent_id, status="active", role="fixer", hours=1):
    now = datetime.now(timezone.utc)
    return {
        "lease_id": lease_id,
        "item_id": item_id,
        "agent_id": agent_id,
        "role": role,
        "status": status,
        "created_at": now,
        "expires_at": now + timedelta(hours=hours),
        "resume_token": f"resume:req_{lease_id}",
        "request_hash": "hash-1",
        "request_id": f"req_{lease_id}",
        "conflict_keys": [],
    }


class LeaseRecoveryCommandTest(unittest.TestCase):
    def _session(self, lease, *, item_state="claimed"):
        item = github_thread("github-thread:A")
        item["state"] = item_state
        item["active_lease_id"] = lease["lease_id"]
        item["claimed_by"] = lease["agent_id"]
        return {
            "session_id": "s1",
            "repo": "owner/repo",
            "pr_number": "801",
            "items": {item["item_id"]: item},
            "leases": {lease["lease_id"]: lease},
        }

    def _recovery(self, session, lease, *, agent_id, role="fixer"):
        from gh_address_cr.core.leases import calculate_lease_recovery_state

        return calculate_lease_recovery_state(
            session,
            lease["lease_id"],
            agent_id=agent_id,
            role=role,
            item_id=lease["item_id"],
            request_hash=str(lease["request_hash"]),
        ).to_dict()

    def test_owner_of_an_active_lease_gets_an_actionable_command(self):
        lease = _lease("L1", item_id="github-thread:A", agent_id="fixer-1")
        recovery = self._recovery(self._session(lease), lease, agent_id="fixer-1")

        self.assertEqual(recovery["reason_code"], "LEASE_ACTIVE")
        self.assertIn("resume_command", recovery)
        # Must not hand back the call that produced LEASE_LOCKED_ITEM.
        self.assertNotIn("agent next", recovery["resume_command"])
        self.assertIn("agent submit", recovery["resume_command"])

    def test_a_lease_owned_by_another_agent_gets_no_command(self):
        lease = _lease("L2", item_id="github-thread:A", agent_id="other-agent")
        recovery = self._recovery(self._session(lease), lease, agent_id="fixer-1")

        self.assertEqual(recovery["reason_code"], "LEASE_RECOVERY_STOP")
        self.assertIsNone(recovery.get("resume_command"))

    def test_recovery_outcome_stays_within_the_validated_enum(self):
        from gh_address_cr.core.models import LEASE_RECOVERY_OUTCOMES, LeaseRecoveryState

        lease = _lease("L3", item_id="github-thread:A", agent_id="fixer-1")
        recovery = self._recovery(self._session(lease), lease, agent_id="fixer-1")

        self.assertIn(recovery["recovery_outcome"], LEASE_RECOVERY_OUTCOMES)
        # Round-trips through the validating reader an older agent would use.
        self.assertEqual(LeaseRecoveryState.from_dict(recovery).reason_code, "LEASE_ACTIVE")


class LeaseRemediationTest(unittest.TestCase):
    def test_lease_locked_item_no_longer_falls_back_to_the_generic_text(self):
        from gh_address_cr.core import protocol_codes
        from gh_address_cr.core.remediation import remediation_for

        remediation = remediation_for(protocol_codes.LEASE_LOCKED_ITEM, repo="owner/repo", pr_number="801")

        self.assertNotIn(GENERIC_FALLBACK_MARKER, remediation["summary"])
        self.assertIn("lease_recovery", remediation["summary"])
        self.assertIn("agent leases", remediation["command"])

    def test_reclaim_success_payload_carries_remediation(self):
        # The recovery surface is entirely on the success path (exit 0), where
        # WorkflowError.to_summary never runs.
        from gh_address_cr.core import leases
        from gh_address_cr.core.session import SessionManager

        with tempfile.TemporaryDirectory() as tmp:
            with patch.dict(os.environ, {"GH_ADDRESS_CR_STATE_DIR": tmp}, clear=False):
                manager = SessionManager("owner/repo", "802")
                session = manager.create(status="WAITING_FOR_FIX")
                lease = _lease("L4", item_id="github-thread:A", agent_id="fixer-1")
                item = github_thread("github-thread:A")
                item["active_lease_id"] = "L4"
                session["items"] = {item["item_id"]: item}
                session["leases"] = {"L4": lease}
                manager.save(session)

                payload = leases.reclaim_leases("owner/repo", "802")

                self.assertEqual(payload["expired_count"], 0)
                remediation = payload["remediation"]
                # Must explain why a non-expired lease was left alone.
                self.assertIn("TTL", remediation["summary"])
                self.assertIn("agent leases", remediation["command"])


class RemediationCommandsAreRunnableTest(unittest.TestCase):
    """Every command a remediation names must be runnable exactly as written.

    Prose-spelled commands drift: the item-mode `agent next` in the LEASE_LOCKED_ITEM
    text and the `agent reclaim` in the reclaim payload were both written by hand and
    both lost the `gh-address-cr` prefix, so an agent copy-pasting either got nothing.
    Generating them from `command_templates` is the fix; this is the guard.
    """

    CLI_START = re.compile(r"^(agent|final-gate|address|review|threads|adapter|active-pr|findings)\s")

    CODES = (
        "RESPONSE_FILE_NOT_FOUND",
        "NO_ACTIVE_PR_SCOPE",
        "MISSING_CLASSIFICATION",
        "MISSING_CLASSIFICATION_NOTE",
        "MISSING_ANYTHING",
        "UNREGISTERED_CODE",
    )

    def _bare_commands(self, text):
        return [span for span in re.findall(r"`([^`]+)`", text) if self.CLI_START.match(span)]

    def test_no_remediation_names_a_command_without_its_entrypoint(self):
        from gh_address_cr.core import protocol_codes
        from gh_address_cr.core.remediation import remediation_for

        codes = list(self.CODES) + [
            protocol_codes.LEASE_LOCKED_ITEM,
            protocol_codes.MISSING_PUBLISH_REPLY,
            protocol_codes.MISSING_FIX_REPLY_COMMIT_HASH,
        ]
        for code in codes:
            with self.subTest(reason_code=code):
                remediation = remediation_for(code, repo="owner/repo", pr_number="801")
                self.assertEqual(self._bare_commands(remediation["summary"]), [])
                self.assertTrue(remediation["command"].startswith("gh-address-cr "))

    def test_the_reclaim_success_payload_names_runnable_commands_too(self):
        # The success path carries its own remediation, and is reached with exit 0, so it
        # never passes through remediation_for and needs its own guard.
        from gh_address_cr.core import leases
        from gh_address_cr.core.session import SessionManager

        with tempfile.TemporaryDirectory() as tmp:
            with patch.dict(os.environ, {"GH_ADDRESS_CR_STATE_DIR": tmp}, clear=False):
                manager = SessionManager("owner/repo", "806")
                session = manager.create(status="WAITING_FOR_FIX")
                item = github_thread("github-thread:A")
                session["items"] = {item["item_id"]: item}
                manager.save(session)

                remediation = leases.reclaim_leases("owner/repo", "806")["remediation"]

                self.assertEqual(self._bare_commands(remediation["summary"]), [])
                self.assertTrue(remediation["command"].startswith("gh-address-cr "))


if __name__ == "__main__":
    unittest.main()
